[ci]
runtime = "nix"
runner = "atlas-nix-trusted"
workspace = true
step_runners = { cargo-clippy = "atlas-nix-trusted", cargo-doc = "atlas-nix-trusted", cargo-fmt = "atlas-nix-trusted", cargo-package = "atlas-nix-trusted", cargo-test = "atlas-nix-trusted", nix-check = "atlas-nix-trusted", quality-tools = "atlas-nix-trusted" }
publish_crates = true

[ci.pages]
repo = "caniko/rs-harbor"
canonical_domain = "rs-harbor.tartanoglu.com"
source_branch = "main"
