//! Attic JWT token decode, status, and expiry helpers.
//!
//! These are shared between canix and rs-harbor's own CLI.  The pure functions
//! (decode, status) are hosted here so version skew between the two consumers
//! does not produce different token-expiry judgments.

use anyhow::{Result, anyhow};
use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use serde::Deserialize;
use serde_json::Value;
use std::time::Duration;

/// Decoded payload of an Attic JWT.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct JwtPayload {
    pub exp: i64,
    pub nbf: i64,
    pub sub: String,
    #[serde(rename = "https://jwt.attic.rs/v1")]
    pub attic_scopes: Value,
}

/// Human-readable token expiry status.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum JwtStatus {
    Valid { expires_in: Duration },
    Expired { ago: Duration },
    NotYetValid { in_: Duration },
}

/// Decode the payload segment of a JWT without verifying the signature.
///
/// Attic JWTs are signed with the cache's Ed25519 keypair.  We decode without
/// verification only for *user-facing diagnostics* — the server performs real
/// verification.  This lets `canix cache health` and `canix cache recover`
/// tell the operator "your token is still valid" without needing the public
/// key at the client.
pub fn decode_payload(token: &str) -> Result<JwtPayload> {
    let mut parts = token.split('.');
    let _header = parts
        .next()
        .ok_or_else(|| anyhow!("malformed JWT: missing header"))?;
    let payload = parts
        .next()
        .ok_or_else(|| anyhow!("malformed JWT: missing payload"))?;
    let _signature = parts
        .next()
        .ok_or_else(|| anyhow!("malformed JWT: missing signature"))?;
    if parts.next().is_some() {
        return Err(anyhow!("malformed JWT: too many segments"));
    }

    let decoded = URL_SAFE_NO_PAD
        .decode(payload)
        .map_err(|e| anyhow!("decode JWT payload: {e}"))?;
    serde_json::from_slice(&decoded).map_err(|e| anyhow!("parse JWT payload JSON: {e}"))
}

/// Determine the status of a JWT payload relative to a clock value (`now`).
///
/// `now` is a Unix timestamp in seconds (typically `Utc::now().timestamp()`).
/// Keeping it injectable lets callers pin time in tests.
#[must_use]
pub fn status(payload: &JwtPayload, now: i64) -> JwtStatus {
    if payload.nbf > now {
        return JwtStatus::NotYetValid {
            in_: Duration::from_secs((payload.nbf - now).cast_unsigned()),
        };
    }
    if payload.exp <= now {
        return JwtStatus::Expired {
            ago: Duration::from_secs((now - payload.exp).cast_unsigned()),
        };
    }
    JwtStatus::Valid {
        expires_in: Duration::from_secs((payload.exp - now).cast_unsigned()),
    }
}

/// Format a `Duration` for human-display (e.g. "3 days 2 hours").
#[must_use]
pub fn format_duration(d: Duration) -> String {
    let total_secs = d.as_secs();
    let days = total_secs / 86400;
    let hours = (total_secs % 86400) / 3600;
    let minutes = (total_secs % 3600) / 60;

    match (days, hours, minutes) {
        (0, 0, m) => format!("{m} min"),
        (0, h, m) => format!("{h}h {m} min"),
        (d, h, _) => format!("{d}d {h}h"),
    }
}

/// Format a Unix timestamp for display (e.g. "2026-06-15 14:30").
#[must_use]
pub fn format_timestamp(ts: i64) -> String {
    use chrono::TimeZone;
    chrono::Utc
        .timestamp_opt(ts, 0)
        .single()
        .map_or_else(
            || format!("ts={ts}"),
            |dt| dt.format("%Y-%m-%d %H:%M:%S UTC").to_string(),
        )
}

#[cfg(test)]
mod tests {
    use super::*;

    // A JWT with known-payload, generated by Attic for a test cache.
    // The header + signature are valid-looking base64 but we never verify
    // the signature, so any properly-structured JWT works for unit tests.
    const VALID_JWT: &str = "eyJhbGciOiJFZDI1NTE5In0.eyJleHAiOjE4OTM0NTYwMDAsIm5iZiI6MTY3MjUzNzIwMCwic3ViIjoidGVzdC11c2VyIiwiaHR0cHM6Ly9qd3QuYXR0aWMucnMvdjEiOiJjYWNoZTp0ZXN0LXB1c2gifQ.7E3d2QqJgPzFz8QqJgPzFz8QqJgPzFz8QqJgPzFz8Q";

    #[test]
    fn decode_valid_jwt() {
        let payload = decode_payload(VALID_JWT).unwrap();
        assert_eq!(payload.sub, "test-user");
        assert_eq!(payload.exp, 1_893_456_000);
        assert_eq!(payload.nbf, 1_672_537_200);
    }

    #[test]
    fn status_valid() {
        let payload = decode_payload(VALID_JWT).unwrap();
        let s = status(&payload, 1_700_000_000);
        assert_eq!(
            s,
            JwtStatus::Valid {
                expires_in: Duration::from_secs(193_456_000)
            }
        );
    }

    #[test]
    fn status_expired() {
        let payload = decode_payload(VALID_JWT).unwrap();
        let s = status(&payload, 1_893_456_001);
        assert_eq!(
            s,
            JwtStatus::Expired {
                ago: Duration::from_secs(1)
            }
        );
    }

    #[test]
    fn status_not_yet_valid() {
        let payload = decode_payload(VALID_JWT).unwrap();
        let s = status(&payload, 1_000_000_000);
        assert_eq!(
            s,
            JwtStatus::NotYetValid {
                in_: Duration::from_secs(672_537_200)
            }
        );
    }

    #[test]
    fn malformed_jwt() {
        assert!(decode_payload("not-a-jwt").is_err());
        assert!(decode_payload("a.b").is_err());
        assert!(decode_payload("a.b.c.d").is_err());
    }

    #[test]
    fn format_duration_short() {
        assert_eq!(format_duration(Duration::from_secs(45)), "0 min");
        assert_eq!(format_duration(Duration::from_secs(120)), "2 min");
    }

    #[test]
    fn format_duration_days() {
        assert_eq!(format_duration(Duration::from_hours(25)), "1d 1h");
        assert_eq!(format_duration(Duration::from_hours(168)), "7d 0h");
    }
}
