# mkAtticPush :: { pkgs, adapter, paths?, flake?, closures? }
#             -> { type = "app"; program = "..."; }
#
# Build a Nix app that pushes store paths to an Attic binary cache.
# Run with: nix run .#push-cache
#
# Usage (Rust project flake):
#   apps.push-cache = harbor.lib.mkAtticPush {
#     inherit pkgs;
#     adapter = infra.harborAdapter;
#     paths = [ self.packages.${system}.default ];
#   };
let
  adapterLib = import ./adapter.nix;
in
  {
    pkgs,
    adapter,
    paths ? [],
    flake ? null,
    closures ? true,
  }:
    assert pkgs.lib.assertMsg (adapterLib.isHarborAdapter adapter)
    "rs-harbor: mkAtticPush 'adapter' must be a harbor adapter (from mkAdapter)";
    assert pkgs.lib.assertMsg (builtins.isList paths)
    "rs-harbor: mkAtticPush 'paths' must be a list of derivations or store paths";
    assert pkgs.lib.assertMsg (builtins.length paths > 0 || flake != null)
    "rs-harbor: mkAtticPush requires non-empty 'paths' or a 'flake' reference";
    assert pkgs.lib.assertMsg (flake == null || builtins.isString flake)
    "rs-harbor: mkAtticPush 'flake' must be null or a string";
    assert pkgs.lib.assertMsg (builtins.isBool closures)
    "rs-harbor: mkAtticPush 'closures' must be a bool"; let
      inherit (adapter.attic) endpoint cache tokenEnvVar serverName;

      pathStrings = map (p: "${p}") paths;
      pathsShell = builtins.concatStringsSep " " (map pkgs.lib.escapeShellArg pathStrings);
      flakeShell = pkgs.lib.escapeShellArg (
        if flake == null
        then ""
        else flake
      );

      script = pkgs.writeShellApplication {
        name = "harbor-attic-push";
        runtimeInputs = [pkgs.attic-client pkgs.coreutils pkgs.jq pkgs.nix];
        text =
          ''
            # Harbor Attic Push — generated by rs-harbor
            TOKEN="''${${tokenEnvVar}:-}"
            if [[ -z "''${TOKEN//[[:space:]]/}" || "$TOKEN" == *[!A-Za-z0-9._-]* ]]; then
              echo "ERROR: ${tokenEnvVar} must be a nonempty Attic JWT." >&2
              exit 1
            fi

            tmp="$(mktemp -d)"
            trap 'rm -rf "$tmp"' EXIT
            export XDG_CONFIG_HOME="$tmp/config"
            install -d -m 0700 "$XDG_CONFIG_HOME/attic"
            attic_config="$XDG_CONFIG_HOME/attic/config.toml"
            install -m 0600 /dev/null "$attic_config"
            {
              printf 'default-server = "%s"\n' ${pkgs.lib.escapeShellArg serverName}
              printf '[servers.%s]\n' ${pkgs.lib.escapeShellArg serverName}
              printf 'endpoint = "%s"\n' ${pkgs.lib.escapeShellArg endpoint}
              printf 'token = "%s"\n' "$TOKEN"
            } > "$attic_config"
            test "$(stat -c '%a' "$attic_config")" = 600

            manifest="''${HARBOR_ATTIC_MANIFEST:-$tmp/paths}"
            : > "$manifest"
          ''
          + (
            if pathStrings != []
            then ''
              PATHS=(${pathsShell})
            ''
            else ""
          )
          + (
            if flake != null
            then ''
              echo "Archiving flake inputs..."
              nix flake archive --json --no-write-lock-file ${flakeShell} \
                | jq -r '.. | objects | .path? // empty' >> "$manifest"
            ''
            else ""
          )
          + (
            if closures && pathStrings != []
            then ''
              echo "Resolving closures..."
              nix path-info -r "''${PATHS[@]}" >> "$manifest"
            ''
            else if pathStrings != []
            then ''
              printf '%s\n' "''${PATHS[@]}" >> "$manifest"
            ''
            else ""
          )
          + ''
            sort -u -o "$manifest" "$manifest"
            test -s "$manifest"
            echo "Pushing to ${serverName}:${cache}..."
            attic push --stdin --no-closure --ignore-upstream-cache-filter \
              "${serverName}:${cache}" < "$manifest"

            echo "Done. Pushed to ${serverName}:${cache}."
          '';
      };
    in {
      type = "app";
      program = "${script}/bin/harbor-attic-push";
    }
