# mkAtticPush :: { pkgs, adapter, paths, closures? }
#             -> { type = "app"; program = "..."; }
#
# Build a Nix app that pushes store paths to an Attic binary cache.
# Run with: nix run .#push-cache
#
# Usage (Rust project flake):
#   apps.push-cache = harbor.lib.mkAtticPush {
#     inherit pkgs;
#     adapter = infra.harborAdapter;
#     paths = [ self.packages.${system}.default ];
#   };
let
  adapterLib = import ./adapter.nix;
in
  {
    pkgs,
    adapter,
    paths,
    closures ? true,
  }:
    assert pkgs.lib.assertMsg (adapterLib.isHarborAdapter adapter)
    "rs-harbor: mkAtticPush 'adapter' must be a harbor adapter (from mkAdapter)";
    assert pkgs.lib.assertMsg (builtins.isList paths)
    "rs-harbor: mkAtticPush 'paths' must be a list of derivations or store paths";
    assert pkgs.lib.assertMsg (builtins.length paths > 0)
    "rs-harbor: mkAtticPush 'paths' must not be empty";
    assert pkgs.lib.assertMsg (builtins.isBool closures)
    "rs-harbor: mkAtticPush 'closures' must be a bool"; let
      inherit (adapter.attic) endpoint cache tokenEnvVar serverName;

      pathStrings = map (p: "${p}") paths;
      pathsSpaced = builtins.concatStringsSep " " pathStrings;

      script = pkgs.writeShellApplication {
        name = "harbor-attic-push";
        runtimeInputs = [pkgs.attic-client pkgs.nix];
        text =
          ''
            # Harbor Attic Push — generated by rs-harbor
            TOKEN="''${${tokenEnvVar}:-}"
            if [ -z "$TOKEN" ]; then
              echo "ERROR: ${tokenEnvVar} is not set." >&2
              echo "  export ${tokenEnvVar}=<your-attic-token>" >&2
              exit 1
            fi

            echo "Logging in to ${endpoint} as '${serverName}'..."
            attic login "${serverName}" "${endpoint}" "$TOKEN"

            PATHS="${pathsSpaced}"
          ''
          + (
            if closures
            then ''
              echo "Resolving closures..."
              # shellcheck disable=SC2086
              RESOLVED=$(nix-store -qR $PATHS | sort -u)
            ''
            else ''
              RESOLVED="$PATHS"
            ''
          )
          + ''
            echo "Pushing to ${serverName}:${cache}..."
            # shellcheck disable=SC2086
            attic push "${serverName}:${cache}" $RESOLVED

            echo "Done. Pushed to ${serverName}:${cache}."
          '';
      };
    in {
      type = "app";
      program = "${script}/bin/harbor-attic-push";
    }
