# minisign signing/verification apps — generated by harbor-rs.
#
# mkMinisignSign :: { pkgs, files, secretKeyEnvVar?, passwordEnvVar?,
#                     comment?, trustedComment? }
#                -> { type = "app"; program = "..."; }
# mkMinisignVerify :: { pkgs, files, publicKeyFile? }
#                  -> { type = "app"; program = "..."; }
#
# These wrap the exact `minisign -S` / `minisign -V` invocation that release
# pipelines hand-roll (e.g. signing SHA256SUMS.txt), as one reusable,
# shellcheck'd app. The secret key + its password are read from environment
# variables at runtime (never baked into the store); the signer writes the key
# to a private temp file with a cleanup trap.
#
# Usage (Rust project flake):
#   apps.sign-release = harbor.lib.mkMinisignSign {
#     inherit pkgs;
#     files = [ "release/SHA256SUMS.txt" ];
#   };
#   apps.verify-release = harbor.lib.mkMinisignVerify {
#     inherit pkgs;
#     files = [ "release/SHA256SUMS.txt" ];
#   };
#
# Run with: MINISIGN_SECRET_KEY=... MINISIGN_PASSWORD=... nix run .#sign-release
{
  mkMinisignSign = {
    pkgs,
    files,
    secretKeyEnvVar ? "MINISIGN_SECRET_KEY",
    passwordEnvVar ? "MINISIGN_PASSWORD",
    comment ? null,
    trustedComment ? null,
  }:
    assert pkgs.lib.assertMsg (builtins.isList files)
    "harbor-rs: mkMinisignSign 'files' must be a list of path strings";
    assert pkgs.lib.assertMsg (builtins.length files > 0)
    "harbor-rs: mkMinisignSign 'files' must not be empty";
    assert pkgs.lib.assertMsg (builtins.all builtins.isString files)
    "harbor-rs: mkMinisignSign 'files' entries must be strings";
    assert pkgs.lib.assertMsg (comment == null || builtins.isString comment)
    "harbor-rs: mkMinisignSign 'comment' must be a string";
    assert pkgs.lib.assertMsg (trustedComment == null || builtins.isString trustedComment)
    "harbor-rs: mkMinisignSign 'trustedComment' must be a string"; let
      filesBash = builtins.concatStringsSep " " (map pkgs.lib.escapeShellArg files);
      commentArg =
        if comment == null
        then ""
        else " -c ${pkgs.lib.escapeShellArg comment}";
      trustedArg =
        if trustedComment == null
        then ""
        else " -t ${pkgs.lib.escapeShellArg trustedComment}";

      script = pkgs.writeShellApplication {
        name = "harbor-minisign-sign";
        runtimeInputs = [pkgs.minisign pkgs.coreutils];
        text = ''
          # Harbor minisign sign — generated by harbor-rs
          SECKEY="''${${secretKeyEnvVar}:-}"
          PASSWORD="''${${passwordEnvVar}:-}"
          if [ -z "$SECKEY" ]; then
            echo "ERROR: ${secretKeyEnvVar} is not set." >&2
            echo "  export ${secretKeyEnvVar}=<password-protected minisign secret key>" >&2
            exit 1
          fi
          if [ -z "$PASSWORD" ]; then
            echo "ERROR: ${passwordEnvVar} is not set." >&2
            exit 1
          fi

          umask 077
          keyfile="$(mktemp)"
          trap 'rm -f "$keyfile"' EXIT
          printf '%s' "$SECKEY" > "$keyfile"

          files=( ${filesBash} )
          for file in "''${files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "ERROR: file to sign does not exist: $file" >&2
              exit 1
            fi
            echo "Signing $file -> $file.minisig"
            printf '%s\n' "$PASSWORD" | \
              minisign -S -s "$keyfile" -m "$file" -x "$file.minisig"${commentArg}${trustedArg}
          done

          echo "Done. Signed ${toString (builtins.length files)} file(s)."
        '';
      };
    in {
      type = "app";
      program = "${script}/bin/harbor-minisign-sign";
    };

  mkMinisignVerify = {
    pkgs,
    files,
    publicKeyFile ? "keys/minisign.pub",
  }:
    assert pkgs.lib.assertMsg (builtins.isList files)
    "harbor-rs: mkMinisignVerify 'files' must be a list of path strings";
    assert pkgs.lib.assertMsg (builtins.length files > 0)
    "harbor-rs: mkMinisignVerify 'files' must not be empty";
    assert pkgs.lib.assertMsg (builtins.all builtins.isString files)
    "harbor-rs: mkMinisignVerify 'files' entries must be strings";
    assert pkgs.lib.assertMsg (builtins.isString publicKeyFile)
    "harbor-rs: mkMinisignVerify 'publicKeyFile' must be a string"; let
      filesBash = builtins.concatStringsSep " " (map pkgs.lib.escapeShellArg files);
      pubArg = pkgs.lib.escapeShellArg publicKeyFile;

      script = pkgs.writeShellApplication {
        name = "harbor-minisign-verify";
        runtimeInputs = [pkgs.minisign pkgs.coreutils];
        text = ''
          # Harbor minisign verify — generated by harbor-rs
          if [ ! -s ${pubArg} ]; then
            echo "ERROR: minisign public key not found: ${publicKeyFile}" >&2
            echo "  commit the project's public key (e.g. keys/minisign.pub)." >&2
            exit 1
          fi

          files=( ${filesBash} )
          for file in "''${files[@]}"; do
            if [ ! -f "$file.minisig" ]; then
              echo "ERROR: signature not found: $file.minisig" >&2
              exit 1
            fi
            echo "Verifying $file against ${publicKeyFile}"
            minisign -V -p ${pubArg} -m "$file" -x "$file.minisig"
          done

          echo "Done. Verified ${toString (builtins.length files)} signature(s)."
        '';
      };
    in {
      type = "app";
      program = "${script}/bin/harbor-minisign-verify";
    };
}
